def get_states() -> dict:
    state_dict = {
        0: "PB",
        1: "RJ",
        2: "MG",
        3: "SP",
        4: "RS",
        5: "SC",
        6: "PR",
        7: "MS",
        8: "MT",
        9: "GO",
        10: "DF",
        11: "ES",
        12: "BA",
        13: "SE",
        14: "AL",
        15: "PE",
        16: "RN",
        17: "PB",
        18: "CE",
        19: "PI",
        20: "MA",
        21: "PA",
        22: "AP",
        23: "AM",
        24: "RO",
        25: "AC",
        26: "RR",
    }
    return state_dict
